FROM nginx

COPY ApiGateways/nginx/nginx.local.conf /etc/nginx/nginx.conf
COPY ApiGateways/nginx/id-local.eshopping.com.crt /etc/ssl/certs/id-local.eshopping.com.crt
COPY ApiGateways/nginx/id-local.eshopping.com.key /etc/ssl/private/id-local.eshopping.com.key