version: '3.4'

services:
  catalogdb:
    image: mongo:latest

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres:14-alpine

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  portainer:
    image: portainer/portainer-ce:latest
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  ocelot.apigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways/Ocelot.ApiGateway/Dockerfile

  eshopping.identity:
    image: ${DOCKER_REGISTRY-}eshoppingidentity
    build:
      context: .
      dockerfile: Infrastructure/EShopping.Identity/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:




